### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by liftedkilt**

### CODE REVIEW

**Comment by liftedkilt** [comment]
atlantis plan

**Comment by liftedkilt** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ null_resource.example
      id: <computed>

  + null_resource.second_example
      id: <computed>
Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /root/.atlantis/repos/liftedkilt/atlantis-test/6/default/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/liftedkilt/atlantis-test/6/default/default.tfplan"


```

* To **discard** this plan click [here](http://e0761cb1.ngrok.io/lock?id=liftedkilt%252Fatlantis-test%252F.%252Fdefault).

**Comment by liftedkilt** [comment]
Locks and plans deleted for the projects and environments modified in this pull request:

- path: `liftedkilt/atlantis-test/.` environment: `default`

**Comment by sampecsek** [comment]
atlantis apply

**Comment by liftedkilt** [comment]
Atlantis commands can't be run on closed pull requests

**Pull request merged**
