### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by sampecsek**

### CODE REVIEW

**Comment by sampecsek** [comment]
atlantis plan

**Comment by liftedkilt** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ null_resource.2345
      id: <computed>

  + null_resource.asdffdsa
      id: <computed>

  + null_resource.example
      id: <computed>

  + null_resource.second_example
      id: <computed>
Plan: 4 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /root/.atlantis/repos/liftedkilt/atlantis-test/5/default/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/liftedkilt/atlantis-test/5/default/default.tfplan"


```

* To **discard** this plan click [here](http://e0761cb1.ngrok.io/lock?id=liftedkilt%252Fatlantis-test%252F.%252Fdefault).

**Comment by sampecsek** [comment]
aTlAnTis PlAN

**Comment by sampecsek** [comment]
atlantis plan

**Comment by liftedkilt** [comment]
Atlantis plan

**Comment by liftedkilt** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ null_resource.2345
      id: <computed>

  + null_resource.asdffdsa
      id: <computed>

  + null_resource.example
      id: <computed>

  + null_resource.second_example
      id: <computed>
Plan: 4 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /root/.atlantis/repos/liftedkilt/atlantis-test/5/default/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/liftedkilt/atlantis-test/5/default/default.tfplan"


```

* To **discard** this plan click [here](http://e0761cb1.ngrok.io/lock?id=liftedkilt%252Fatlantis-test%252F.%252Fdefault).

**Comment by sampecsek** [comment]
ATLANTIS PLAN

**Comment by sampecsek** [comment]
Atlantis Plan

**Comment by sampecsek** [comment]
atlantis apply

**Comment by liftedkilt** [comment]
**Apply Failed**: No workspace found. Did you run plan?

**Comment by sampecsek** [comment]
atlantis plan

**Comment by liftedkilt** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ null_resource.2345
      id: <computed>

  + null_resource.asdffdsa
      id: <computed>

  + null_resource.example
      id: <computed>

  + null_resource.second_example
      id: <computed>
Plan: 4 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /root/.atlantis/repos/liftedkilt/atlantis-test/5/default/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/liftedkilt/atlantis-test/5/default/default.tfplan"


```

* To **discard** this plan click [here](http://e0761cb1.ngrok.io/lock?id=liftedkilt%252Fatlantis-test%252F.%252Fdefault).

**Comment by sampecsek** [comment]
atlantis apply

**Comment by liftedkilt** [comment]
```diff
null_resource.second_example: Creating...
null_resource.example: Creating...
null_resource.asdffdsa: Creating...
null_resource.2345: Creating...
null_resource.second_example: Creation complete after 0s (ID: 8641264372626794116)
null_resource.2345: Creation complete after 0s (ID: 8042737633937823380)
null_resource.example: Creation complete after 0s (ID: 9203190652366155546)
null_resource.asdffdsa: Creation complete after 0s (ID: 3278744294134685973)

Apply complete! Resources: 4 added, 0 changed, 0 destroyed.

```

**Comment by liftedkilt** [comment]
atlantis plan

**Comment by liftedkilt** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ null_resource.2345
      id: <computed>

  + null_resource.asdffdsa
      id: <computed>

  + null_resource.example
      id: <computed>

  + null_resource.second_example
      id: <computed>
Plan: 4 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /root/.atlantis/repos/liftedkilt/atlantis-test/5/default/default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/root/.atlantis/repos/liftedkilt/atlantis-test/5/default/default.tfplan"


```

* To **discard** this plan click [here](http://e0761cb1.ngrok.io/lock?id=liftedkilt%252Fatlantis-test%252F.%252Fdefault).

**Comment by liftedkilt** [comment]
Locks and plans deleted for the projects and environments modified in this pull request:

- path: `liftedkilt/atlantis-test/.` environment: `default`

**Pull request closed without merging**
